# Generated by Django 5.0.6 on 2024-05-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('weather', models.CharField(choices=[('Tropical', 'Tropical'), ('Seco', 'Seco'), ('Templado', 'Templado'), ('Continental', 'Continental'), ('Fríos', 'Fríos'), ('Cualquiera', 'Cualquiera')], default='Cualquiera', max_length=20)),
                ('image', models.ImageField(upload_to='task_images/')),
                ('quantity', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('Principiante', 'Principiante'), ('Medio', 'Medio'), ('Difícil', 'Difícil')], default='Principiante', max_length=20)),
                ('season', models.CharField(choices=[('Primavera', 'Primavera'), ('Verano', 'Verano'), ('Otoño', 'Otoño'), ('Invierno', 'Invierno'), ('Cualquiera', 'Cualquiera')], default='Cualquiera', max_length=20)),
                ('illumination', models.CharField(choices=[('Sol', 'Sol'), ('Media sombra', 'Media sombra'), ('Sombra', 'Sombra')], default='Sol', max_length=20)),
                ('type', models.CharField(choices=[('Hortalizas', 'Hortalizas'), ('Flores', 'Flores'), ('Aromáticas', 'Aromáticas')], max_length=20)),
            ],
        ),
    ]
