# Generated by Django 5.0.6 on 2024-05-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Cultivos',
        ),
    ]
